import Head from 'next/head'
import Header from '../Header/Header'
import styles from '../../styles/Home.module.css'
export default function Layout({ children, home }) {
    return (<div className={styles.container}>
        <Head>
            <title>Edwin Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta charset='utf-8' />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header home={home}/>
        <main className={styles.main}>
            {children}
        </main>
    </div>)
}