import Head from 'next/head'
import Header from './Header'

export default function Layout({ children, home }) {
    return (<div>
        <Head>
            <title>Edwin Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header home={home}/>
        <main className='center container'>
            {children}
        </main>
    </div>)
}