import Head from 'next/head'
import Header from './Header'
import IconBar from './IconBar'

export default function Layout({ children, home }) {
    return (<div>
        <Head>
            <title>Edwin Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='general-container'>
            <Header home={home} />
            {home && <IconBar />}
            {home
                ?
                <main className='home-main center container'>
                    {children}
                </main>
                :
                <main className='main center container'>
                    {children}
                </main>
            }
        </div>
    </div>)
}