import Head from 'next/head'
import Link from "next/link"
import Header from '../components/Header/Header'
import styles from '../styles/Home.module.css'


export default function Home() {
    return (
    <div className={styles.container}>
      <Head>
        <title>Edwin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header home/>
      <main className={styles.main}>
        <Link href="/blog"><a>Blog</a></Link>
      </main>
    </div>
  )
}
