import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from "graphql-request"
import BlogCard from "../components/BlogCard"

const graphcms = new GraphQLClient("https://api-sa-east-1.graphcms.com/v2/cl468i5n71qhe01ywbvsa8io8/master")

const QUERY = gql`
  {
    posts {
      id, 
         title, 
         datePublish, 
         slug,
       content{
         html
       }
       author{
         username,
         avatar{
           url
         }
       }
       coverPhoto{
         url
       }
       
     }
  }
`
export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY)
  return {
    props: {
      posts
    },
    revalidate: 10,
  }
}

export default function Home({ posts }) {
  console.log(posts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          posts.map(post => {
            return <BlogCard 
              key={post.id} 
              title={post.title}
              author={post.author}
              coverPhoto={post.coverPhoto.url}
              slug={post.slug}

            />
          })
        }
      </main>
    </div>
  )
}
